# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd453c1d665b5376eec835f692169e6dbb9b1a6f843eaba20b8ff440a82401f220217c4aef866a0febdece8fa980a168823e7bcb6b22eeb3485210d03218e9cd

test:
  secret_key_base: d0e5f81c674a9c355102b9c9556d62d2d69f1d69cbc1d42e7204cff7627d68b1f8ba80bdde9d54c75c7aaa55fe6e65a5d72908ec7888e0453fca19c175f04a0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
